Repository google/tsunami-security-scanner-plugins, pull requests merged in 2025-08, with the labels that each got.

#608 AI PRP: pyZMQ deserialization RCE
  py_plugins/pyzmq_deserialization_rce/pyzmq_deserialization_rce.py
  py_plugins/pyzmq_deserialization_rce/pyzmq_deserialization_rce_test.py
Labels: lgtm, python

#602 AI PRP: RAGFlow unsafe RPC server
  py_plugins/ragflow_deserialization_rce/ragflow_deserialization_rce.py
  py_plugins/ragflow_deserialization_rce/ragflow_deserialization_rce_test.py
Labels: lgtm, python

#594 Improved implementation of Spark CVE-2022-33891 detector
  community/detectors/apache_spark_cve_2022_33891/build.gradle
  community/detectors/apache_spark_cve_2022_33891/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202233891/Annotations.java
  community/detectors/apache_spark_cve_2022_33891/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202233891/Cve202233891VulnDetector.java
  community/detectors/apache_spark_cve_2022_33891/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202233891/Cve202233891VulnDetectorBootstrapModule.java
  community/detectors/apache_spark_cve_2022_33891/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202233891/Cve202233891VulnDetectorConfigs.java
  community/detectors/apache_spark_cve_2022_33891/src/test/java/com/google/tsunami/plugins/detectors/cves/cve202233891/Cve202233891DetectorTest.java
  community/detectors/apache_spark_cve_2022_33891/src/test/java/com/google/tsunami/plugins/detectors/cves/cve202233891/Cve202233891DetectorWithCallbackServerTest.java
Labels: lgtm, doyensec

#660 Add Langflow CVE-2025-3248 Scanner
  templated/templateddetector/plugins/cve/2025/Langflow_CVE_2025_3248.textproto
  templated/templateddetector/plugins/cve/2025/Langflow_CVE_2025_3248_test.textproto
Labels: lgtm

#552 kubeflow weak credential tester
  google/detectors/credentials/generic_weak_credential_detector/src/main/java/com/google/tsunami/plugins/detectors/credentials/genericweakcredentialdetector/GenericWeakCredentialDetectorBootstrapModule.java
  google/detectors/credentials/generic_weak_credential_detector/src/main/java/com/google/tsunami/plugins/detectors/credentials/genericweakcredentialdetector/testers/kubeflow/KubeflowCredentialTester.java
  google/detectors/credentials/generic_weak_credential_detector/src/main/resources/detectors/credentials/genericweakcredentialdetector/data/service_default_credentials.textproto
  google/detectors/credentials/generic_weak_credential_detector/src/test/java/com/google/tsunami/plugins/detectors/credentials/genericweakcredentialdetector/testers/kubeflow/KubeflowCredentialTesterTest.java
  google/fingerprinters/web/src/main/java/com/google/tsunami/plugins/fingerprinters/web/WebServiceFingerprinter.java
Labels: lgtm, credentials
